In [4]:
import tvm
from tvm import relax
from tvm.relax.frontend.torch import from_exported_program

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import torchvision.models as models
from torchvision.io import read_image
from torch.export import export

import onnx
import os

# Resnet model

In [7]:
from torchvision.models.resnet import ResNet34_Weights, resnet34
torch_model = resnet34(weights=ResNet34_Weights.DEFAULT).eval()

Downloading: "https://download.pytorch.org/models/resnet34-b627a593.pth" to /home/leobraginski/.cache/torch/hub/checkpoints/resnet34-b627a593.pth

100.0%

IRModule

In [8]:
# Give an example argument to torch.export
example_args = (torch.randn(1, 3, 224, 224, dtype=torch.float32),)

# Convert the model to IRModule
with torch.no_grad():
    exported_program = export(torch_model, example_args)
    mod = from_exported_program(exported_program, keep_params_as_input=True)

mod, params = relax.frontend.detach_params(mod)
mod.show()

/usr/lib/python3.12/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

## Optimize model

In [9]:
TOTAL_TRIALS = 512
MAX_TRIALS_PER_TASK = 16 
target = tvm.target.Target({
    "kind": "llvm",
    "mtriple": "riscv64-linux-gnu",
    "mcpu": "generic-rv64",
    "mattr": ["+64bit", "+m", "+a", "+f", "+d", "+c", "+v"],
    "num-cores": 8,
})
work_dir = "tuning_logs"

mod = relax.get_pipeline(
    "static_shape_tuning",
    target=target,
    work_dir=work_dir,
    total_trials=TOTAL_TRIALS,
    max_trials_per_task=MAX_TRIALS_PER_TASK,
)(mod)

# Only show the main function
mod["main"].show()

2026-03-31 16:28:07 [INFO] Logging directory: tuning_logs/logs
2026-03-31 16:28:19 [INFO] LocalBuilder: max_workers = 8
2026-03-31 16:28:21 [INFO] LocalRunner: max_workers = 1
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #0: "transpose"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #1: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #2: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #3: "max_pool2d"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #4: "fused_matmul_add13"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #5: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #6: "fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #7: "fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #8: "fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5"

[16:28:22] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/schedule_rule/apply_custom_rule.cc:60: Warning: Unknown schedule rule "meta_schedule.pool_max" for target keys "["cpu"]". Checked ffi::Functions:
  meta_schedule.cpu.meta_schedule.pool_max

2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #9: "fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #10: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #11: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #12: "reshape"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #13: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #14: "fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:28:22 [INFO] [task_scheduler.cc:168] Initializing Task #15: "mean"
2026-03-31 16:28:23 [INFO] [task_scheduler.cc:168] Initializing Task #16: "fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu"
2026-03-31 16:28:23 [INFO] [task_scheduler.cc:168] Initializing Task #17: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:28:23 [INFO] [task_scheduler.cc:168] Initializing Task #18: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:28:23 [INFO] [task_scheduler.cc:168] Initializing Task #19: "fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,0,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,0,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,0,
3,max_pool2d,1806336,1,N/A,N/A,N/A,0,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,0,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:28:23 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |      0 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |      0 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |      0 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |      0 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:28:23 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:28:23 [INFO] [task_scheduler.cc:202] Sending 1 sample(s) to builder
2026-03-31 16:28:30 [INFO] [task_scheduler.cc:204] Sending 1 sample(s) to runner
2026-03-31 16:28:30 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #1: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"
2026-03-31 16:28:33 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:28:46 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:28:46 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #2: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1"
2026-03-31 16:28:49 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:29:00 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:29:01 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #3: "max_pool2d"
2026-03-31 16:29:03 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:29:16 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:29:16 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #4: "fused_matmul_add13"

[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o

[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/tir/expr.cc:74: Warning: Didn't find variable definition for: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/script/printer/ir/./../utils.h:45: Warning: TVMScript printer falls back to the basic address printer with the error:
Variable is not defined in the environment: v_k_o
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)
[16:29:16] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/meta_schedule/postproc/rewrite_tensorize.cc:47: Warning: Tensorize failed with error (not rendered)

2026-03-31 16:29:18 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:29:49 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:29:50 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #5: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1"
2026-03-31 16:29:53 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:30:05 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:30:05 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #6: "fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:30:08 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:30:20 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:30:20 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #7: "fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11"
2026-03-31 16:30:21 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:30:34 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:30:34 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #8: "fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5"
2026-03-31 16:30:35 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:30:48 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:30:48 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #9: "fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8"
2026-03-31 16:30:50 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:31:00 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:31:00 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #10: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4"
2026-03-31 16:31:03 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:31:24 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:31:24 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #11: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3"
2026-03-31 16:31:27 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:31:37 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:31:37 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:31:38 [INFO] [task_scheduler.cc:202] Sending 1 sample(s) to builder
2026-03-31 16:31:45 [INFO] [task_scheduler.cc:204] Sending 1 sample(s) to runner
2026-03-31 16:31:45 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #13: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2"
2026-03-31 16:31:48 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:32:00 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:32:00 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #14: "fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:32:03 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:32:17 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:32:17 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #15: "mean"
2026-03-31 16:32:18 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:32:28 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:32:28 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #16: "fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu"
2026-03-31 16:32:31 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:33:04 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:33:04 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #17: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:33:07 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:33:18 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:33:18 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #18: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:33:21 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:33:33 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:33:33 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #19: "fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"
2026-03-31 16:33:36 [INFO] [task_scheduler.cc:202] Sending 16 sample(s) to builder
2026-03-31 16:33:53 [INFO] [task_scheduler.cc:204] Sending 16 sample(s) to runner
2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.450000	tr-a-peak@32: 1.000000	tr-rmse: 0.450000	tr-rmse: 0.450000
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.032305	tr-a-peak@32: 1.000000	tr-rmse: 0.032305	tr-rmse: 0.032305
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.002319	tr-a-peak@32: 1.000000	tr-rmse: 0.002319	tr-rmse: 0.002319
2026-03-31 16:33:54 [DEBUG] XGB iter  75: tr-p-rmse: 0.000166	tr-a-peak@32: 1.000000	tr-rmse: 0.000166	tr-rmse: 0.000166
2026-03-31 16:33:54 [DEBUG] XGB iter 100: tr-p-rmse: 0.000012	tr-a-peak@32: 1.000000	tr-rmse: 0.000012	tr-rmse: 0.000012
2026-03-31 16:33:54 [DEBUG] XGB iter 125: tr-p-rmse: 0.000001	tr-a-peak@32: 1.000000	tr-rmse: 0.000001	tr-rmse: 0.000001
2026-03-31 16:33:54 [DEBUG] XGB iter 150: tr-p-rmse: 0.000000	tr-a-peak@32: 1.000000	tr-rmse: 0.000000	tr-rmse: 0.000000
2026-03-31 16:33:54 [DEBUG] XGB iter 175: tr-p-rmse: 0.000000	tr-a-peak@32: 1.000000	tr-rmse: 0.000000	tr-rmse: 0.000000
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [131] tr-p-rmse:0.00000	tr-a-peak@32:1.00000	tr-rmse:0.00000	tr-rmse:0.00000
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #0: "transpose"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,0,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,0,
3,max_pool2d,1806336,1,N/A,N/A,N/A,0,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,0,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |      0 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |      0 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |      0 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |      0 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.216729	tr-a-peak@32: 1.000000	tr-rmse: 0.586034	tr-rmse: 0.586034
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.014787	tr-a-peak@32: 1.000000	tr-rmse: 0.646804	tr-rmse: 0.646804
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.014509	tr-a-peak@32: 1.000000	tr-rmse: 0.646804	tr-rmse: 0.646804
2026-03-31 16:33:54 [DEBUG] XGB iter  75: tr-p-rmse: 0.014509	tr-a-peak@32: 1.000000	tr-rmse: 0.646804	tr-rmse: 0.646804
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [26] tr-p-rmse:0.01448	tr-a-peak@32:1.00000	tr-rmse:0.64697	tr-rmse:0.64697
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #1: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,0,
3,max_pool2d,1806336,1,N/A,N/A,N/A,0,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,0,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |      0 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |      0 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |      0 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.208479	tr-a-peak@32: 1.000000	tr-rmse: 0.593101	tr-rmse: 0.593101
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.011120	tr-a-peak@32: 1.000000	tr-rmse: 0.657027	tr-rmse: 0.657027
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.011122	tr-a-peak@32: 1.000000	tr-rmse: 0.657016	tr-rmse: 0.657016
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01110	tr-a-peak@32:1.00000	tr-rmse:0.65717	tr-rmse:0.65717
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #2: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,0,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,0,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |      0 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |      0 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.209541	tr-a-peak@32: 1.000000	tr-rmse: 0.588107	tr-rmse: 0.588107
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.014735	tr-a-peak@32: 1.000000	tr-rmse: 0.648821	tr-rmse: 0.648821
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.014737	tr-a-peak@32: 1.000000	tr-rmse: 0.648812	tr-rmse: 0.648812
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01471	tr-a-peak@32:1.00000	tr-rmse:0.64892	tr-rmse:0.64892
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #3: "max_pool2d"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,0,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |      0 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.188663	tr-a-peak@32: 1.000000	tr-rmse: 0.572465	tr-rmse: 0.572465
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.014131	tr-a-peak@32: 1.000000	tr-rmse: 0.623375	tr-rmse: 0.623375
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.014133	tr-a-peak@32: 1.000000	tr-rmse: 0.623366	tr-rmse: 0.623366
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01411	tr-a-peak@32:1.00000	tr-rmse:0.62346	tr-rmse:0.62346
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #4: "fused_matmul_add13"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,0,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |      0 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.191234	tr-a-peak@32: 1.000000	tr-rmse: 0.578664	tr-rmse: 0.578664
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.012824	tr-a-peak@32: 1.000000	tr-rmse: 0.633212	tr-rmse: 0.633212
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.012825	tr-a-peak@32: 1.000000	tr-rmse: 0.633205	tr-rmse: 0.633205
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01281	tr-a-peak@32:1.00000	tr-rmse:0.63328	tr-rmse:0.63328
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #5: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,0,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |      0 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #6: "fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,0,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |      0 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.180801	tr-a-peak@32: 1.000000	tr-rmse: 0.570003	tr-rmse: 0.570003
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.013651	tr-a-peak@32: 1.000000	tr-rmse: 0.621055	tr-rmse: 0.621055
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.013652	tr-a-peak@32: 1.000000	tr-rmse: 0.621050	tr-rmse: 0.621050
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01364	tr-a-peak@32:1.00000	tr-rmse:0.62111	tr-rmse:0.62111
2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #7: "fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,0,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |      0 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [INFO] [task_scheduler.cc:246] [Updated] Task #8: "fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,0,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:54 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |      0 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:54 [DEBUG] XGB iter   0: tr-p-rmse: 0.163489	tr-a-peak@32: 1.000000	tr-rmse: 0.558165	tr-rmse: 0.558165
2026-03-31 16:33:54 [DEBUG] XGB iter  25: tr-p-rmse: 0.010170	tr-a-peak@32: 1.000000	tr-rmse: 0.601131	tr-rmse: 0.601131
2026-03-31 16:33:54 [DEBUG] XGB iter  50: tr-p-rmse: 0.010172	tr-a-peak@32: 1.000000	tr-rmse: 0.601126	tr-rmse: 0.601126
2026-03-31 16:33:54 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01016	tr-a-peak@32:1.00000	tr-rmse:0.60117	tr-rmse:0.60117
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #9: "fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,0,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |      0 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #10: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,0,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |      0 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] XGB iter   0: tr-p-rmse: 0.172719	tr-a-peak@32: 1.000000	tr-rmse: 0.565400	tr-rmse: 0.565400
2026-03-31 16:33:55 [DEBUG] XGB iter  25: tr-p-rmse: 0.011239	tr-a-peak@32: 1.000000	tr-rmse: 0.613183	tr-rmse: 0.613183
2026-03-31 16:33:55 [DEBUG] XGB iter  50: tr-p-rmse: 0.011240	tr-a-peak@32: 1.000000	tr-rmse: 0.613179	tr-rmse: 0.613179
2026-03-31 16:33:55 [DEBUG] XGB stopped. Best iteration: [22] tr-p-rmse:0.01123	tr-a-peak@32:1.00000	tr-rmse:0.61322	tr-rmse:0.61322
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #11: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,0,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      0 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #12: "reshape"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,0,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |      0 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #13: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,0,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |      0 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #14: "fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,0,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |      0 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] XGB iter   0: tr-p-rmse: 0.181416	tr-a-peak@32: 1.000000	tr-rmse: 0.571296	tr-rmse: 0.571296
2026-03-31 16:33:55 [DEBUG] XGB iter  25: tr-p-rmse: 0.010482	tr-a-peak@32: 1.000000	tr-rmse: 0.622685	tr-rmse: 0.622685
2026-03-31 16:33:55 [DEBUG] XGB iter  50: tr-p-rmse: 0.010482	tr-a-peak@32: 1.000000	tr-rmse: 0.622685	tr-rmse: 0.622685
2026-03-31 16:33:55 [DEBUG] XGB stopped. Best iteration: [20] tr-p-rmse:0.01048	tr-a-peak@32:1.00000	tr-rmse:0.62272	tr-rmse:0.62272
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #15: "mean"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,0,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |      0 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #16: "fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,0,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |      0 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #17: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,0,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |      0 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] XGB iter   0: tr-p-rmse: 0.187107	tr-a-peak@32: 1.000000	tr-rmse: 0.575236	tr-rmse: 0.575236
2026-03-31 16:33:55 [DEBUG] XGB iter  25: tr-p-rmse: 0.010387	tr-a-peak@32: 1.000000	tr-rmse: 0.628700	tr-rmse: 0.628700
2026-03-31 16:33:55 [DEBUG] XGB iter  50: tr-p-rmse: 0.010387	tr-a-peak@32: 1.000000	tr-rmse: 0.628700	tr-rmse: 0.628700
2026-03-31 16:33:55 [DEBUG] XGB stopped. Best iteration: [20] tr-p-rmse:0.01038	tr-a-peak@32:1.00000	tr-rmse:0.62873	tr-rmse:0.62873
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #18: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,0,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |      0 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:246] [Updated] Task #19: "fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #4: "fused_matmul_add13"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #4 has finished. Remaining task(s): 19

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #11: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #11 has finished. Remaining task(s): 18

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #13: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #13 has finished. Remaining task(s): 17

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #18: "fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #18 has finished. Remaining task(s): 16

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #2: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #2 has finished. Remaining task(s): 15

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #5: "fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #5 has finished. Remaining task(s): 14

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #9: "fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #9 has finished. Remaining task(s): 13

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #17: "fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #17 has finished. Remaining task(s): 12

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #6: "fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2"
2026-03-31 16:33:55 [INFO] [task_scheduler.cc:269] Task #6 has finished. Remaining task(s): 11

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:55 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:246] [Updated] Task #12: "reshape"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:246] [Updated] Task #12: "reshape"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #15: "mean"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #15 has finished. Remaining task(s): 10

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #1: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #1 has finished. Remaining task(s): 9

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #3: "max_pool2d"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #3 has finished. Remaining task(s): 8

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #10: "fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #10 has finished. Remaining task(s): 7

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #16: "fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #16 has finished. Remaining task(s): 6

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #7: "fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11"
2026-03-31 16:33:56 [INFO] [task_scheduler.cc:269] Task #7 has finished. Remaining task(s): 5

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:56 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:246] [Updated] Task #12: "reshape"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #8: "fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:269] Task #8 has finished. Remaining task(s): 4

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #19: "fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:269] Task #19 has finished. Remaining task(s): 3

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:246] [Updated] Task #12: "reshape"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #12: "reshape"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:269] Task #12 has finished. Remaining task(s): 2

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #14: "fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3"
2026-03-31 16:33:57 [INFO] [task_scheduler.cc:269] Task #14 has finished. Remaining task(s): 1

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

2026-03-31 16:33:57 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:246] [Updated] Task #0: "transpose"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:58 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:58 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:246] [Updated] Task #0: "transpose"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:58 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:58 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:58 [INFO] [task_scheduler.cc:246] [Updated] Task #0: "transpose"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:58 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:58 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:33:59 [INFO] [task_scheduler.cc:202] Sending 0 sample(s) to builder
2026-03-31 16:33:59 [INFO] [task_scheduler.cc:204] Sending 0 sample(s) to runner
2026-03-31 16:33:59 [INFO] [task_scheduler.cc:246] [Updated] Task #0: "transpose"

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

2026-03-31 16:33:59 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0


Total trials: 0
Total latency (us): 0

2026-03-31 16:33:59 [INFO] [task_scheduler.cc:189] TaskScheduler picks Task #0: "transpose"
2026-03-31 16:33:59 [INFO] [task_scheduler.cc:269] Task #0 has finished. Remaining task(s): 0

,Name,FLOP,Weight,Speed (GFLOPS),Latency (us),Weighted Latency (us),Trials,Done
0,transpose,1,1,N/A,N/A,N/A,1,Y
1,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,231336448,2,N/A,N/A,N/A,16,Y
2,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1,232415232,3,N/A,N/A,N/A,16,Y
3,max_pool2d,1806336,1,N/A,N/A,N/A,16,Y
4,fused_matmul_add13,1025000,1,N/A,N/A,N/A,16,Y
5,fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1,232214528,3,N/A,N/A,N/A,16,Y
6,fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,116107264,1,N/A,N/A,N/A,16,Y
7,fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11,12945408,1,N/A,N/A,N/A,16,Y
8,fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5,13246464,1,N/A,N/A,N/A,16,Y
9,fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8,13045760,1,N/A,N/A,N/A,16,Y
10,fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4,231361536,3,N/A,N/A,N/A,16,Y
11,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3,231512064,6,N/A,N/A,N/A,16,Y
12,reshape,1,1,N/A,N/A,N/A,1,Y
13,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2,231813120,4,N/A,N/A,N/A,16,Y
14,fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,115856384,1,N/A,N/A,N/A,16,Y
15,mean,25600,1,N/A,N/A,N/A,16,Y
16,fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu,240041984,1,N/A,N/A,N/A,16,Y
17,fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2,231712768,3,N/A,N/A,N/A,16,Y
18,fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3,231461888,5,N/A,N/A,N/A,16,Y
19,fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4,115730944,1,N/A,N/A,N/A,16,Y

Total trials: 0
Total latency (us): 0

2026-03-31 16:33:59 [DEBUG] [task_scheduler.cc:327]
 ID |                                                                                  Name |      FLOP | Weight | Speed (GFLOPS) | Latency (us) | Weighted Latency (us) | Trials | Done
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0 |                                                                             transpose |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
  1 |       fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 231336448 |      2 |            N/A |          N/A |                   N/A |     16 |    Y
  2 |     fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_add3_relu1 | 232415232 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  3 |                                                                            max_pool2d |   1806336 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  4 |                                                                    fused_matmul_add13 |   1025000 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  5 |          fused_conv2d1_subtract1_divide1_expand_dims_multiply1_expand_dims_add2_relu1 | 232214528 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
  6 |        fused_conv2d2_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 116107264 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  7 |            fused_conv2d10_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11 |  12945408 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  8 |              fused_conv2d4_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5 |  13246464 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
  9 |              fused_conv2d7_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8 |  13045760 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 10 | fused_conv2d9_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_add12_relu4 | 231361536 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 11 |   fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_add9_relu3 | 231512064 |      6 |            N/A |          N/A |                   N/A |     16 |    Y
 12 |                                                                               reshape |         1 |      1 |            N/A |          N/A |                   N/A |      1 |    Y
 13 |   fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_add6_relu2 | 231813120 |      4 |            N/A |          N/A |                   N/A |     16 |    Y
 14 |        fused_conv2d5_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 115856384 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 15 |                                                                                  mean |     25600 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 16 |               fused_conv2d_subtract_divide_expand_dims_multiply_expand_dims_add1_relu | 240041984 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
 17 |        fused_conv2d3_subtract2_divide2_expand_dims1_multiply2_expand_dims1_add5_relu2 | 231712768 |      3 |            N/A |          N/A |                   N/A |     16 |    Y
 18 |        fused_conv2d6_subtract3_divide3_expand_dims2_multiply3_expand_dims2_add8_relu3 | 231461888 |      5 |            N/A |          N/A |                   N/A |     16 |    Y
 19 |       fused_conv2d8_subtract4_divide4_expand_dims3_multiply4_expand_dims3_add11_relu4 | 115730944 |      1 |            N/A |          N/A |                   N/A |     16 |    Y
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total trials: 0
Total latency (us): 0

[16:33:59] /home/leobraginski/Desktop/TVM-RVV_optimized_operators/tvm/src/relax/transform/meta_schedule.cc:92: Warning: Creating JSONDatabase. Workload at: tuning_logs/database_workload.json, Tuning records at: tuning_logs/database_tuning_record.json